/* Aaj Kya Khau - curated food data (works fully offline) */

const CUISINES=[
 {id:'indian',n:'Regular Indian'},
 {id:'chinese',n:'Chinese'},
 {id:'pizza',n:'Pizza'},
 {id:'pasta',n:'Pasta'},
 {id:'healthy',n:'Healthy'},
];

/* Eating-out dish ideas. meal: b=breakfast l=lunch s=snack d=dinner n=late night */
const OUT_DISHES=[
 {n:'Masala Dosa',c:'indian',veg:1,vegan:1,meal:'bl',d:'Crisp crepe, spiced potato, sambar and chutneys',at:'South Indian spot or darshini'},
 {n:'Idli Sambar',c:'indian',veg:1,vegan:1,meal:'b',d:'Steamed, light, easy on the stomach',at:'South Indian spot'},
 {n:'Poori Bhaji',c:'indian',veg:1,vegan:1,meal:'b',d:'Fluffy pooris with mild potato bhaji',at:'local breakfast joint'},
 {n:'Paratha with Curd',c:'indian',veg:1,meal:'bl',d:'Aloo or gobi paratha, white butter, cool curd',at:'dhaba or punjabi joint'},
 {n:'Chole Bhature',c:'indian',veg:1,meal:'ld',d:'Spiced chickpeas with puffed bhature',at:'North Indian joint'},
 {n:'Rajma Chawal',c:'indian',veg:1,meal:'ld',d:'Kidney-bean curry over steamed rice',at:'North Indian joint or thali place'},
 {n:'Dal Tadka + Jeera Rice',c:'indian',veg:1,vegan:1,meal:'ld',d:'Ghee-tempered dal, cumin rice',at:'any Indian restaurant'},
 {n:'Palak Paneer + Naan',c:'indian',veg:1,meal:'d',d:'Spinach gravy, soft paneer, buttery naan',at:'North Indian restaurant'},
 {n:'Paneer Tikka',c:'indian',veg:1,meal:'sd',d:'Char-grilled marinated paneer, mint chutney',at:'barbecue or dhaba'},
 {n:'Butter Chicken + Naan',c:'indian',meal:'d',d:'Creamy tomato gravy, tandoori chicken',at:'North Indian restaurant'},
 {n:'Chicken Biryani',c:'indian',meal:'ld',d:'Layered rice, fried onions, raita',at:'biryani house'},
 {n:'Veg Biryani',c:'indian',veg:1,meal:'ld',d:'Seasonal veg, saffron rice, raita',at:'biryani house'},
 {n:'Mutton Rogan Josh + Rice',c:'indian',meal:'d',d:'Slow-cooked Kashmiri-style curry',at:'North Indian / Mughlai'},
 {n:'Fish Curry + Rice',c:'indian',meal:'ld',d:'Coastal-style curry, steamed rice',at:'coastal or Kerala restaurant'},
 {n:'Pav Bhaji',c:'indian',veg:1,meal:'sn',d:'Buttery mash of veg with toasted pav',at:'street-side or chaat house'},
 {n:'Pani Puri',c:'indian',veg:1,vegan:1,meal:'s',d:'Crisp puris, spiced water, tangy chutneys',at:'chaat stall'},
 {n:'Samosa + Chai',c:'indian',veg:1,vegan:1,meal:'sb',d:'The classic evening pairing',at:'tea stall'},
 {n:'Vada Pav',c:'indian',veg:1,vegan:1,meal:'sn',d:'Mumbai\'s burger - spiced potato in pav',at:'street stall'},
 {n:'Kathi Roll (Paneer)',c:'indian',veg:1,meal:'sdn',d:'Flaky paratha wrap, grilled paneer',at:'roll joint'},
 {n:'Kathi Roll (Chicken)',c:'indian',meal:'sdn',d:'Flaky paratha wrap, spiced chicken',at:'roll joint'},
 {n:'Veg Hakka Noodles',c:'chinese',veg:1,meal:'ldn',d:'Wok-tossed noodles, crunchy veg',at:'indo-chinese joint'},
 {n:'Veg Manchurian + Fried Rice',c:'chinese',veg:1,meal:'ld',d:'Saucy veg balls over burnt-garlic rice',at:'indo-chinese joint'},
 {n:'Chilli Chicken',c:'chinese',meal:'sdn',d:'Crisp chicken tossed with peppers and chilli',at:'indo-chinese joint'},
 {n:'Chicken Fried Rice',c:'chinese',meal:'ldn',d:'Smoky wok rice, egg and chicken',at:'indo-chinese joint'},
 {n:'Steamed Momos (Veg)',c:'chinese',veg:1,meal:'sn',d:'Soft dumplings, fiery red chutney',at:'momo stall'},
 {n:'Steamed Momos (Chicken)',c:'chinese',meal:'sn',d:'Juicy dumplings, fiery red chutney',at:'momo stall'},
 {n:'Hot and Sour Soup',c:'chinese',veg:1,meal:'sdn',d:'Peppery, tangy, warming',at:'Chinese restaurant'},
 {n:'Schezwan Noodles',c:'chinese',veg:1,vegan:1,meal:'ldn',d:'Fiery, garlicky, smoky',at:'indo-chinese joint'},
 {n:'Spring Rolls',c:'chinese',veg:1,vegan:1,meal:'s',d:'Crisp rolls, sweet-chilli dip',at:'Chinese restaurant'},
 {n:'Margherita Pizza',c:'pizza',veg:1,meal:'ldn',d:'San Marzano tomato, fresh mozzarella, basil',at:'pizzeria'},
 {n:'Farmhouse Veg Pizza',c:'pizza',veg:1,meal:'ldn',d:'Loaded peppers, onions, corn, mushrooms',at:'pizzeria'},
 {n:'Paneer Tikka Pizza',c:'pizza',veg:1,meal:'ldn',d:'Desi-style, smoky paneer and onions',at:'pizzeria'},
 {n:'Pepperoni Pizza',c:'pizza',meal:'ldn',d:'Classic pepperoni, extra cheese pull',at:'pizzeria'},
 {n:'BBQ Chicken Pizza',c:'pizza',meal:'ldn',d:'Smoky barbecue sauce, grilled chicken',at:'pizzeria'},
 {n:'Pasta Alfredo',c:'pasta',veg:1,meal:'ldn',d:'Creamy parmesan sauce, fettuccine',at:'Italian cafe'},
 {n:'Pasta Arrabbiata',c:'pasta',veg:1,vegan:1,meal:'ldn',d:'Spicy tomato-garlic sauce, penne',at:'Italian cafe'},
 {n:'Aglio e Olio',c:'pasta',veg:1,vegan:1,meal:'ldn',d:'Olive oil, garlic, chilli flakes - simple and perfect',at:'Italian cafe'},
 {n:'Pesto Pasta',c:'pasta',veg:1,meal:'ld',d:'Basil pesto, pine nuts, parmesan',at:'Italian cafe'},
 {n:'Chicken Lasagna',c:'pasta',meal:'dn',d:'Layered, baked, deeply comforting',at:'Italian restaurant'},
 {n:'Mac and Cheese',c:'pasta',veg:1,meal:'sdn',d:'Baked, golden, indulgent',at:'cafe or diner'},
 {n:'Buddha Bowl',c:'healthy',veg:1,vegan:1,meal:'l',d:'Grains, roasted veg, greens, tahini',at:'salad bar or health cafe'},
 {n:'Grilled Chicken Salad',c:'healthy',meal:'ld',d:'Lean protein, crunchy greens, light dressing',at:'health cafe'},
 {n:'Quinoa Power Bowl',c:'healthy',veg:1,vegan:1,meal:'l',d:'Quinoa, avocado, chickpeas, seeds',at:'health cafe'},
 {n:'Smoothie Bowl',c:'healthy',veg:1,meal:'b',d:'Blended fruit, granola, nut butter',at:'juice bar'},
 {n:'Hummus + Pita Platter',c:'healthy',veg:1,vegan:1,meal:'sl',d:'Creamy hummus, warm pita, olives',at:'Levantine cafe'},
 {n:'Grilled Fish + Greens',c:'healthy',meal:'d',d:'Simply grilled, lemon and herbs',at:'grill or seafood place'},
 {n:'Sprouts Chaat',c:'healthy',veg:1,vegan:1,meal:'sb',d:'Protein-rich, tangy, zero guilt',at:'chaat stall or home'},
 {n:'Avocado Toast',c:'healthy',veg:1,meal:'b',d:'Sourdough, smashed avo, chilli flakes',at:'cafe'},
 {n:'Grilled Sandwich + Soup',c:'healthy',veg:1,meal:'ls',d:'Whole-grain toastie, tomato soup',at:'cafe'},
];

/* Home recipes. ing = core ingredients the matcher looks for */
const RECIPES=[
 {n:'Poha',c:'indian',veg:1,vegan:1,t:15,diff:'Easy',meal:'b',ing:['poha','onion','mustard seeds','turmeric','peanuts','lemon'],steps:['Rinse poha in a sieve, rest 5 min to soften.','Heat oil, crackle mustard seeds, add curry leaves, peanuts and chopped onion; soften 3 min.','Add turmeric, salt, a pinch of sugar; fold in poha gently.','Steam 2 min on low, finish with lemon juice and coriander.']},
 {n:'Vegetable Upma',c:'indian',veg:1,t:20,diff:'Easy',meal:'b',ing:['semolina','onion','carrot','peas','mustard seeds','ginger'],steps:['Dry-roast semolina till fragrant; keep aside.','Temper mustard, urad dal, curry leaves, ginger; add onion and chopped veg.','Add 2.5x hot water, salt; pour in semolina slowly while stirring.','Cover 3 min on low; finish with ghee and coriander.']},
 {n:'Besan Chilla',c:'indian',veg:1,t:15,diff:'Easy',meal:'bs',ing:['besan','onion','tomato','green chilli','coriander'],steps:['Whisk besan with water to a pouring batter; add salt, turmeric, ajwain.','Fold in chopped onion, tomato, chilli, coriander.','Pour a ladle on a hot tawa, spread thin, drizzle oil.','Cook 2 min per side till golden; serve with chutney or curd.']},
 {n:'Masala Omelette',c:'indian',egg:1,t:10,diff:'Easy',meal:'bs',ing:['eggs','onion','tomato','green chilli','coriander'],steps:['Beat eggs with salt, pepper, a pinch of turmeric.','Mix in finely chopped onion, tomato, chilli, coriander.','Cook on a medium-hot pan with oil, 2 min per side.','Fold and serve with toast or pav.']},
 {n:'Aloo Paratha',c:'indian',veg:1,t:35,diff:'Medium',meal:'bld',ing:['wheat flour','potato','green chilli','coriander','ghee','cumin'],steps:['Knead a soft wheat-flour dough; rest 15 min.','Mash boiled potato with salt, cumin, chilli, coriander, amchur.','Stuff a dough ball, roll gently into a thick disc.','Cook on hot tawa with ghee till golden spots both sides. Serve with curd and pickle.']},
 {n:'Vegetable Khichdi',c:'indian',veg:1,vegan:1,t:30,diff:'Easy',meal:'ld',ing:['rice','moong dal','carrot','peas','turmeric','cumin','ghee'],steps:['Wash equal parts rice and moong dal.','Pressure cook with 3x water, turmeric, salt, chopped veg - 3 whistles.','Temper ghee with cumin, hing, ginger; pour over.','Rest 5 min; serve with curd, papad and a spoon of ghee.']},
 {n:'Dal Tadka',c:'indian',veg:1,vegan:1,t:30,diff:'Easy',meal:'ld',ing:['toor dal','onion','tomato','garlic','cumin','ghee','red chilli'],steps:['Pressure cook toor dal with turmeric and salt - 3 whistles; whisk smooth.','Simmer with chopped tomato 5 min.','Temper ghee with cumin, garlic, dried red chilli, hing; pour over dal.','Finish with coriander and lemon; serve with rice or roti.']},
 {n:'Aloo Gobi',c:'indian',veg:1,vegan:1,t:30,diff:'Easy',meal:'ld',ing:['potato','cauliflower','onion','tomato','turmeric','cumin','ginger'],steps:['Saute cumin and ginger in oil; add onion till golden.','Add tomato, turmeric, coriander powder, salt; cook till oil separates.','Add potato and cauliflower florets; coat well.','Cover and cook on low 15 min, stirring twice. Garnish with coriander.']},
 {n:'Palak Paneer',c:'indian',veg:1,t:35,diff:'Medium',meal:'d',ing:['spinach','paneer','onion','tomato','garlic','cream','garam masala'],steps:['Blanch spinach 2 min, plunge in cold water, blend smooth.','Saute onion, garlic, tomato with cumin; cook down 6 min.','Add spinach puree, salt, garam masala; simmer 5 min.','Add paneer cubes and a swirl of cream; rest 2 min. Serve with roti or rice.']},
 {n:'Chole (Chickpea Curry)',c:'indian',veg:1,vegan:1,t:40,diff:'Medium',meal:'ld',ing:['chickpeas','onion','tomato','ginger','garlic','chole masala'],steps:['Soak chickpeas overnight (or use canned, drained).','Pressure cook with salt till soft - 5-6 whistles.','Fry onion-ginger-garlic paste till deep golden; add tomato and chole masala.','Add chickpeas with some cooking water; simmer 10 min. Finish with coriander, onion rings, lemon.']},
 {n:'Bhindi Fry',c:'indian',veg:1,vegan:1,t:25,diff:'Easy',meal:'ld',ing:['okra','onion','turmeric','cumin','amchur'],steps:['Wash and fully dry okra; cut into 1-inch pieces.','Fry okra in oil on medium-high, uncovered, till edges crisp - 12 min.','Add sliced onion, turmeric, salt; cook 5 min more.','Finish with amchur or lemon. Serve with dal and roti.']},
 {n:'Jeera Aloo',c:'indian',veg:1,vegan:1,t:20,diff:'Easy',meal:'ld',ing:['potato','cumin','turmeric','green chilli','coriander'],steps:['Boil or microwave potatoes till just tender; cube them.','Crackle cumin in oil with green chilli.','Add potato, turmeric, salt; toss on high till edges crisp.','Finish with coriander and a squeeze of lemon.']},
 {n:'Egg Curry',c:'indian',egg:1,t:30,diff:'Medium',meal:'ld',ing:['eggs','onion','tomato','ginger','garlic','garam masala'],steps:['Boil eggs 9 min, peel, score lightly, fry in a little oil till golden.','Cook onion-tomato-ginger-garlic masala till oil separates.','Add turmeric, chilli, garam masala, salt and a cup of water; simmer 5 min.','Add eggs, simmer 3 min; finish with coriander. Serve with rice or roti.']},
 {n:'Paneer Bhurji',c:'indian',veg:1,t:15,diff:'Easy',meal:'bld',ing:['paneer','onion','tomato','green chilli','turmeric','capsicum'],steps:['Saute onion and capsicum 3 min; add tomato, turmeric, salt.','Cook till tomato softens; add pav-bhaji or garam masala.','Crumble in paneer; toss 2 min on high.','Finish with coriander; serve with toast, pav or roti.']},
 {n:'Veg Fried Rice',c:'chinese',veg:1,vegan:1,t:25,diff:'Easy',meal:'ldn',ing:['rice','carrot','beans','capsicum','spring onion','soy sauce','garlic'],steps:['Cook rice ahead and cool it completely (day-old is best).','Stir-fry garlic and chopped veg on the highest flame, 3 min, keeping crunch.','Add rice, soy sauce, pepper, salt; toss on high 3 min.','Finish with spring-onion greens and a few drops of sesame oil.']},
 {n:'Hakka Noodles',c:'chinese',veg:1,vegan:1,t:25,diff:'Easy',meal:'ldn',ing:['noodles','cabbage','carrot','capsicum','spring onion','soy sauce'],steps:['Boil noodles al dente; rinse cold, toss with a little oil.','Flash-fry shredded veg and garlic on high flame 2 min.','Add noodles, soy, vinegar, pepper; toss hard 2 min.','Top with spring-onion greens.']},
 {n:'Veg Manchurian',c:'chinese',veg:1,t:40,diff:'Medium',meal:'ldn',ing:['cabbage','carrot','capsicum','maida','cornflour','soy sauce','garlic','spring onion'],steps:['Squeeze moisture from grated cabbage-carrot; bind with maida, cornflour, salt, pepper.','Shape balls; deep or air fry till deep golden.','Simmer garlic, spring-onion whites, soy, chilli sauce, a cornflour slurry into a glossy sauce.','Toss balls in sauce just before serving; garnish with greens.']},
 {n:'Pasta Arrabbiata',c:'pasta',veg:1,vegan:1,t:25,diff:'Easy',meal:'ldn',ing:['pasta','tomato','garlic','chilli flakes','olive oil','basil'],steps:['Boil pasta in well-salted water; save a cup of pasta water.','Sizzle sliced garlic and chilli flakes in olive oil - do not brown.','Add chopped tomato or passata; simmer 8 min.','Toss pasta in the sauce with a splash of pasta water; finish with basil.']},
 {n:'Pasta Alfredo',c:'pasta',veg:1,t:25,diff:'Easy',meal:'ldn',ing:['pasta','butter','garlic','cream','parmesan','pepper'],steps:['Boil pasta; save a cup of pasta water.','Melt butter with garlic 1 min; add cream and simmer 3 min.','Whisk in grated parmesan till glossy; season with pepper.','Toss pasta through with pasta water as needed; serve immediately.']},
 {n:'Aglio e Olio',c:'pasta',veg:1,vegan:1,t:20,diff:'Easy',meal:'ldn',ing:['pasta','garlic','olive oil','chilli flakes','parsley'],steps:['Boil spaghetti; save a cup of pasta water.','Warm a generous pool of olive oil with thin garlic slices on low till pale gold.','Add chilli flakes, then pasta and a splash of pasta water; toss till silky.','Finish with parsley and more oil.']},
 {n:'Veg Pulao',c:'indian',veg:1,vegan:1,t:30,diff:'Easy',meal:'ld',ing:['rice','carrot','peas','beans','onion','whole spices','ghee'],steps:['Soak basmati 20 min.','Temper ghee with bay, cardamom, cinnamon, cumin; brown sliced onion.','Add chopped veg, rice, 1.75x hot water, salt.','Cook covered on low 12 min; rest 5. Fluff and serve with raita.']},
 {n:'Tomato Rasam',c:'indian',veg:1,vegan:1,t:20,diff:'Easy',meal:'ld',ing:['tomato','tamarind','garlic','pepper','cumin','curry leaves'],steps:['Simmer chopped tomato with tamarind water, crushed garlic, pepper, cumin 10 min.','Mash lightly; thin with water to a broth; add salt.','Temper ghee with mustard, curry leaves, dried chilli, hing; pour in.','Do not boil after tempering. Sip as soup or pour over rice.']},
 {n:'Curd Rice',c:'indian',veg:1,t:15,diff:'Easy',meal:'ld',ing:['rice','curd','milk','ginger','curry leaves','pomegranate'],steps:['Mash cooked rice while warm with a splash of milk.','Cool, then fold in whisked curd and salt.','Temper oil with mustard, curry leaves, ginger, green chilli; mix in.','Top with pomegranate or grapes. Serve cool.']},
 {n:'Sprouts Salad',c:'healthy',veg:1,vegan:1,t:10,diff:'Easy',meal:'bs',ing:['sprouts','onion','tomato','cucumber','lemon','chaat masala'],steps:['Rinse sprouts; steam 3 min if you prefer them soft.','Chop onion, tomato, cucumber fine.','Toss everything with lemon juice, salt, chaat masala.','Finish with coriander; eat fresh.']},
 {n:'Oats Vegetable Porridge',c:'healthy',veg:1,t:15,diff:'Easy',meal:'b',ing:['oats','carrot','peas','onion','mustard seeds','turmeric'],steps:['Temper mustard and curry leaves; soften onion, carrot, peas 3 min.','Add turmeric, salt, 2.5x water; bring to a boil.','Stir in rolled oats; simmer 4 min till creamy.','Rest 2 min; finish with pepper and a little ghee.']},
 {n:'Grilled Cheese Sandwich',c:'healthy',veg:1,t:10,diff:'Easy',meal:'bs',ing:['bread','cheese','butter','tomato','pepper'],steps:['Butter the outside of the bread slices.','Layer cheese and tomato inside; season with pepper.','Grill on a medium pan, pressing gently, till deep golden both sides.','Rest 1 min before cutting - the cheese sets.']},
 {n:'Banana Smoothie',c:'healthy',veg:1,t:5,diff:'Easy',meal:'bs',ing:['banana','milk','oats','honey','cinnamon'],steps:['Add banana, milk, a spoon of oats, honey and cinnamon to a blender.','Blend 45 seconds till completely smooth.','Add ice and blend 10 seconds more if you like it cold.']},
 {n:'Egg Fried Rice',c:'chinese',egg:1,t:20,diff:'Easy',meal:'ldn',ing:['rice','eggs','spring onion','carrot','soy sauce','garlic'],steps:['Scramble eggs on high flame in a little oil; keep aside.','Stir-fry garlic, carrot, spring-onion whites 2 min.','Add cold cooked rice, soy, pepper; toss on high.','Fold eggs back in; finish with greens.']},
 {n:'Chicken Curry (Home Style)',c:'indian',t:45,diff:'Medium',meal:'ld',ing:['chicken','onion','tomato','ginger','garlic','curd','garam masala'],steps:['Marinate chicken in curd, turmeric, salt 20 min (or while you chop).','Brown onions well; add ginger-garlic paste, then tomato; cook till oil separates.','Add chicken and powdered spices; sear 5 min.','Add hot water to cover; simmer 18 min till tender. Rest 5, garnish with coriander.']},
 {n:'Egg Bhurji',c:'indian',egg:1,t:12,diff:'Easy',meal:'bsn',ing:['eggs','onion','tomato','green chilli','turmeric'],steps:['Soften onion in oil; add tomato, turmeric, salt; cook 3 min.','Lower flame, pour in beaten eggs.','Stir gently in folds till just set - still soft.','Finish with coriander and pepper; serve with pav or toast.']},
];

const MEALS={b:'Breakfast',l:'Lunch',s:'Snack',d:'Dinner',n:'Late night'};
const SLOT_HOURS=[[5,11,'b'],[11,16,'l'],[16,19,'s'],[19,23,'d']]; // else 'n'
const WORKER='https://divine-guide.ankitsamriwal.workers.dev/chat';
const APP_NAME='Aaj Kya Khau';
